name: Some cron job
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch
jobs:
  cron-task:
    name: Cron task
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Git log
        run: git log