name: Some cron job
on:
  push:
    branch:
      - master
  # workflow_dispatch
  # schedule:
  #   - cron: '0 0 * * *'
jobs:
  cron-task:
    name: Cron task
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Check if changed in last 24 hrs
        run: |
          set -x \
          LAST_COMMIT_TIMESTAMP=$(git show -s --format=%ct) \
          NOW_TIMESTAMP=$(date +%s) \
          TIME_SINCE_LAST_COMMIT=`expr $NOW_TIMESTAMP - $LAST_COMMIT_TIMESTAMP` \
          echo "LAST_COMMIT_TIMESTAMP: $LAST_COMMIT_TIMESTAMP" \
          echo "NOW_TIMESTAMP: $NOW_TIMESTAMP" \
          echo "TIME_SINCE_LAST_COMMIT: $TIME_SINCE_LAST_COMMIT" \
          if [ $TIME_SINCE_LAST_COMMIT -lt 86400 ]; then echo ::set-env name=SHOULD_RUN::true; fi
      - name: Be happy
        if: env.SHOULD_RUN == 'true'
        run: echo "HAPPY! 🔥"
      - name: Not happy
        if: env.SHOULD_RUN != 'true'
        run: echo "NOT HAPPY! 🐝"